# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38f68c09035011d7db8e73be5c602cb47d28c1dbe99ea2e7ec2af865759aa32b691b438d5373f2a0354c8bf511741622ecff4345d1afb0e40781b93065b1b3ca

test:
  secret_key_base: 31fbd640e998fb360de80e3aa441e1a87c033ce41e89da8907f45978ee92ce9df4ed0e5bedc046389ebc81138ff7ba2571102ea85bdd51a3913f6d7b1d48b934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
